### ISSUE TITLE
the model of Rotary Encoder

### ISSUE THREAD

**Issue by Landau-Randall** [casdata/OP-FM-Shield#1]
could you tell me the model of rotary Encoder knob?

**Comment by casdata** [comment]
Hi Landau-Randall,  the model is the EC11, you can find it in [Aliexpress ](https://www.aliexpress.com/item/4000755931777.html?spm=a2g0o.detail.1000060.1.48f63a46eyJkTm&gps-id=pcDetailBottomMoreThisSeller&scm=1007.13339.291025.0&scm_id=1007.13339.291025.0&scm-url=1007.13339.291025.0&pvid=340e41b6-d87d-4f35-93a1-3b553f208879&_t=gps-id:pcDetailBottomMoreThisSeller,scm-url:1007.13339.291025.0,pvid:340e41b6-d87d-4f35-93a1-3b553f208879,tpp_buckets:668%232846%238113%231998&pdp_ext_f=%7B"sku_id"%3A"10000007329345591"%2C"sceneId"%3A"3339"%7D&pdp_npi=2%40dis%21USD%212.72%212.72%21%21%21%21%21%40210312ee16644289897832056e1a16%2110000007329345591%21rec)

**Comment by Ming-Kerr** [comment]
Hello.
I just completed a build and it booted first go.
I chose EC11 24 indent full step and have a strange problem.
The encoders turn the opposite way they are supposed to.
Is there an easy fix in the code to reverse the rotation direction?
Cheers.
Phil.

**Comment by Ming-Kerr** [comment]
To solve my own problem, lol, I found the part in the code and reversed the logic:

void checkLimitOfKnob(int selectedKnob){

    switch(selectedKnob){
        case 0:
        if(knobACount < 0){
            knobACount = 0;
            knobA.write(0);
            **knobARight** = true;
        }
        else if(knobACount > 0){
            knobACount = 0;
            knobA.write(0);
            **knobALeft** = true;
            //knobA.write(maxLimit * 2);
        }
        break;
        case 1:
        if(knobBCount < 0){
            knobBCount = 0;
            knobB.write(0);
            **knobBRight** = true;
        }
        else if(knobBCount > 0){
            knobBCount = 0;
            knobB.write(0);
            **knobBLeft** = true;
            //knobB.write(maxLimit * 2);
        }
        break;
    }

**Comment by casdata** [comment]
Hi Ming-Kerr, thanks for pointing out the issue and solving it.
