### ISSUE TITLE
Versions used in compile

### ISSUE THREAD

**Issue by Ming-Kerr** [casdata/OP-FM-Shield#2]
Hello.
Can you reply with the versions used for compile: Arduino IDE and the main include libraries please?

I cannot get the software to read the SDcard and have had this problem before in other apps due to library versions incompatibility.

Thanks.

**Comment by casdata** [comment]
Hi Mr. Ming-Kerr, I just compile and test the board on a PC without Arduino, a clean install, and it worked with the Arduino IDE 2.0.3, the used libraries are the last available versions:
MIDI Library by Francois Best (5.0.2)
Adafruit GFX Library by Arduino (1.11.5)
Adafruit BusIO (1.14.1)
Adafruit ST7735 and ST7789 Libray by Adafruit (1.10.0)
Adafruit seesaw Library by Adafruit (1.6.3)
SD by Arduino, SparkFun (1.2.4)
Encoder by Paul Stoffregen (1.4.2)
ArduinoThread by Ivan Seidel (2.1.1)
DueTimer by IvanSeidel (1.4.7)

I notice that I forgot to add the "SD by Arduino, SparkFun" library in the README, so please check that's installed. Also when installing Adafruit GDX Library and the Adafruit ST7735 and ST7789 Library from the library manager allow the installation of all the dependencies or companion libraries when prompted.

Hope this fixes your issue :)

**Comment by Ming-Kerr** [comment]
I have it fully working now.
I had two problems:

1) the VGM folder doesn't seem to read subfolders. I'd put the vgm files in subfolders :)
2) The first YMF262 I installed was faulty. Luckily I had another one...

All good!
